### PR TITLE
Home work has benn done.

### PR DESCRIPTION
**Pull request by Sarmat92**

### CODE REVIEW

**Review by Pshenichnyi-Aleksey — APPROVED** [review]

**Review by 2LAI — APPROVED** [review]

**Review by AnzhelaKhamitskaya — APPROVED** [review]
Lgfm

**Review by DenisAbramovDm — APPROVED** [review]
Lgfm

**Comment by GardDen** [comment]
Судя по единственному коммиту. Эта работа сделана неправильно. В ней просто написано Hello world. Необходимо переделать.

**Comment by alqaesi** [comment]
#GRAMMAR PRACTICE

TASK1

1 He usually has breakfast at 6 a.m. 2 Anyone who smokes 20 cigarettes a day can expect to have health problems. 3 She doesn't like cooking, but today she bakes a pie. 4 I am finishing the project right now. 5 I don't listen to rock music very often. 6 — What does your sister do? — She is a programmer.

TASK2

1 Do you usually work on Saturdays? 2 Listen! Somebody singing. 3 Look! The sun is shining. 4 He doesn't use his car every day. 5 — Where do you come from? ( Where are you from) — I am from Canada. 6 What's happened? Why are you crying?

TASK3

1 He is a good musician, but he doesn't perform very often. 2 I don't go to the gym on Mondays because I usually finish my work very late. 3 Please turn off the laptop, you aren't using it. 4 I don't like tea, but today, I'm drinking it. 5 It's dark in your room. Are you sleeping?

#VOCABULARY PRACTICE TASK 1

1 to execute - выполнять 2 to transfer - перемещать 3 to compile - составлять 4 to pass to - перейти к 5 to switch - переключать 6 to support - поддерживать 7 to retool - переделать (переоборудовать) 8 to implement - выполнить 9 to run a program - запустить программу 10 to enable - обеспечить 11 to utilize - использовать 12 language features - особенности языка 13 multithreaded - многопоточный 14 electronic appliance - электронное устройство 15 embedded systems - перечень задач 16 to complete a course - завершить курс 17 to require - требовать 18 optional - необязательный 19 assignment - задание 20 to expand - расширять 21 to assist - помогать 22 to allow - позволять (давать возможность) 23 to contain - содержать 24 placeholder - поле(метка) 25 lowercase letter - строчная (маленькая буква) 26 capital letter - заглавная буква 27 purpose - цель (задача) 28 variable - переменная 29 discouraged - нерекомендованный 30 to avoid - избегать 31 backlog - долг ( задание) 32 analytics engine - аналитическая машина 33 distibuted search - распределительный поиск

TASK 2

1 The task must be executed correctly and completely. 2 She assisted her brother with his homework. 3 The company I work for is expanding internationally. 4 The students got a homework assignment. 5 This task is optional, so you don't have to do it. 6 This job requires analytical skills. 7 When you complete the course, you will be a programmer. 8 An embedded system is a computer hardware system with software in it. 9 This shop sells good electronic appliances. 10 Java is a multi-threaded programming language which means we can develop a multi-threaded program using Java. 11 Object-oriented, platform-independent, simple, secure are the main features of Java programming. 12 Network video products utilize network bandwidth and storage space based on their configuration. 13 A distributed search engine is a search engine without a central server. 14 Computerization should enable us to cut production cost.
15 Make sure that you have permission to run the program. 16 We began to implement this new method last September. 17 We will need to retool the car industry and retrain workers. 18 Tech support didn't fix her computer problem. 19 Use the switch statement to select one of many code blocks to be executed. 20 The football player passed the ball two times before he took a shot. 21 She compiled a report for her boss. 22 I want to transfer some funds from my account to another account. 23 We haven't begun to focus on a polished user interface, the current user interface is a placeholder. 24 My boss doesn't allow me to use the telephone. 25 The papers contain the bank details of all bank workers. 26 This test has all capital and lower case letters in random order. 27 Our teacher explained to us the purpose of the variable. 28 JavaScript variables are containers for storing data values. 29 Use of Perl/shell style comments ( ) is discouraged. 30 He's a good programmer and can give you some tips to avoid common coding mistakes. 31 I have a big backlog of work to do.

TASK 3

1.Configure the properties used to execute a Web method using an HTTP connection. 2.Configure the properties required to transfer a SQL Server database between two instances of SQL Server 3.Now that your kernel is configured, it is time to compile and install it. 4.Afterwards click the button "Forward" to pass to the next step. 5.Allow me to switch into English. 6.It simply creates a needless bone of contention, and we urge delegations not to support this draft resolution. 7.We should shut down and retool. 8.The challenge now was to implement those commitments. 9.To run a program on Blue Gene/L, a partition of the computer was first to be reserved. 10.However, their effectiveness is limited, requiring funding and technical support to enable adequate responses. 11.With regard to the recruitment of consultants and trainers, the Centre has strived to utilize the services of qualified women as much as possible. 12.Described language features were implemented with help of program icalc.icn by Stephen B. Wampler. 13.There is a built in own file multithreaded FTP server in MyChat. 14.The company also provides installation and repair services for electronic appliances. 15.Green Hills Software is a privately owned company that builds operating systems and programming tools for embedded systems. 16. This procedure provides opportunities to complete a course and to take exams 17.The issue appeared to require further research and study. 18.Participation in these is optional, and usually entails joining a separate Masonic body. 19.I have your first assignment here somewhere 20.The intention is to expand this programme support 21. MTC in particular could be asked to assist in developing these institutions. 22.The selection procedure should be flexible enough to allow for speedy processing. 23.Use these devices to contain it. 24.Later in the fax document, click the placeholder to enter the actual data. 25.If a lowercase letter is entered, it is automatically converted to a capital letter 26.Furthermore, a capital letter (from A to M) should follow the type approval number. 27.Its purpose is to consolidate language and mathematics.Its purpose is to consolidate language and mathematics. 28.Unable to generate the XSD. The variable does not contain XML data. 29.The term "local zone" is specifically discouraged, since in this usage "local" is not an antonym of "global". 30.Obviously we'd like to avoid that information getting out. 31.I got a backlog here. 32.The Analytical Engine was a proposed mechanical general-purpose computer designed by English mathematician and computer pioneer Charles Babbage,[2][3] with the assistance of Ada Lovelace. 33.Distributed search is a search engine model in which the tasks of Web crawling, indexing and query processing are distributed among multiple computers and networks.

**Pull request merged**
