### PR TITLE
Tulai_HW_Eng_Part2

### PR DESCRIPTION
**Pull request by 2LAI**
Grammar Task 2 - done

### CODE REVIEW

**Review by yurasava — APPROVED** [review]

**Review by Kati-Urban — APPROVED** [review]
Nice )

**Review by Pshenichnyi-Aleksey — APPROVED** [review]
Nice work!

**Review by Pshenichnyi-Aleksey — APPROVED** [review]
lgfm

**Comment by 2LAI** [comment]
Part_2 - done

**Comment by 2LAI** [comment]
> lgfm
what do you mean?

**Pull request merged**
