### PR TITLE
English homework1

### PR DESCRIPTION
**Pull request by potapov-alex**
English HW1 make

### CODE REVIEW

**Review by Donutella-tech — CHANGES_REQUESTED** [review]

**Comment by potapov-alex** [comment]
get

**Comment by potapov-alex** [comment]
needed te req

**Review by potapov-alex — COMMENTED** [review]
take it

**Review by DenisAbramovDm — CHANGES_REQUESTED** [review]
Wrong dirrectory. You should put this homework in rpaS3/homework/English/your_name/
And name your file according to content.

**Pull request closed without merging**
